# This workflow performs functions that must occur before launching all the Python tests
# The cache will detect if any of the extra downloads need an update and, if so, will
# fail the workflow. This is required so a maintainer can manually delete the existing
# cache. Deliberate updates to the cache is important to keep track the health and
# status of the cache instead of automatic updates
# Then launch the Python tests in parallel

name: Prebuild

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Extras
        id: cache-extras
        uses: actions/cache@v4
        with:
          path: ~/.isofit
          key: cache-extras

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install ISOFIT
        shell: bash
        run: |
          python3 -m pip install --editable ".[test]"

      - if: steps.cache-extras.outputs.cache-hit == 'true'
        name: Check for Updates
        shell: bash
        run: |
          # Module must report "[x]" to be detected
          if isofit download all --check | grep "\[x]"; then
            # Run it twice, once for detecting updates and once for the job output
            isofit download all --check
            echo "::error::Cache update needed, please request a maintainer to delete the cache-extras then rerun this workflow"
            exit 1
          else
            echo "No cache update needed"
          fi

      - if: steps.cache-extras.outputs.cache-hit != 'true'
        name: Download Extras
        shell: bash
        run: |
          echo "Downloading extras"
          isofit download all
          echo "Building examples"
          isofit build

  pip:
    needs: cache
    uses: ./.github/workflows/test_pip.yml

  path:
    needs: cache
    uses: ./.github/workflows/test_path.yml
